type: object
requires: ["capi_user", "capi_pass", "homeserver_url", "homeserver", "admins"]
properties:
  capi_url:
    type: string
  capi_user:
    type: string
  capi_pass:
    type: string
  homeserver_url:
    type: string
  homeserver:
    type: string
  admins:
    type: array
    items:
      - type: string
    minItems: 1
    uniqueItems: true
